/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg1_carlosnuila;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Nuila
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFcrearUsuario = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuarioNuevo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contraseñaNueva = new javax.swing.JTextField();
        fechaNacimiento = new javax.swing.JTextField();
        numeroTelefono = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        bt_crearUsuario = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        nombreCompleto = new javax.swing.JTextField();
        generoFavorito = new javax.swing.JComboBox<>();
        jFadministrador = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AgregarLibro = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jt_añoPublicacion = new javax.swing.JTextField();
        jt_edicion = new javax.swing.JTextField();
        jt_autor = new javax.swing.JTextField();
        jt_copias = new javax.swing.JTextField();
        jt_titulo = new javax.swing.JTextField();
        rb_2 = new javax.swing.JRadioButton();
        rb_3 = new javax.swing.JRadioButton();
        rb_5 = new javax.swing.JRadioButton();
        rb_1 = new javax.swing.JRadioButton();
        rb_4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTdescripcion = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jb_crearLibro = new javax.swing.JButton();
        cb_genero = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        j_valor = new javax.swing.JTextField();
        Modificar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jt_añoPublicacionnuevo = new javax.swing.JTextField();
        jt_edicionNuevo = new javax.swing.JTextField();
        jt_autorNuevo = new javax.swing.JTextField();
        jt_copiasNuevo = new javax.swing.JTextField();
        jt_tituloNuevo = new javax.swing.JTextField();
        rb_2_ = new javax.swing.JRadioButton();
        rb_3_ = new javax.swing.JRadioButton();
        rb_5_ = new javax.swing.JRadioButton();
        rb_1_ = new javax.swing.JRadioButton();
        rb_4_ = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTdescripcionNuevo = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jb_modificarLibro = new javax.swing.JButton();
        cb_libros = new javax.swing.JComboBox<>();
        EliminarLibro = new javax.swing.JButton();
        nuevoGenero = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jt_valor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        grupoPuntaje = new javax.swing.ButtonGroup();
        jFUsuario = new javax.swing.JFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        cb_librosAdquiridos = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        cb_libroadquiridos = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        cb_amigos = new javax.swing.JComboBox<>();
        PrestarLibro = new javax.swing.JButton();
        panelSolicitudes = new javax.swing.JPanel();
        AgregarAmigo = new javax.swing.JButton();
        cb_solicitudes = new javax.swing.JComboBox<>();
        panelAgregarAmigos = new javax.swing.JPanel();
        EnviarSolicitud = new javax.swing.JButton();
        cb_Usuarios = new javax.swing.JComboBox<>();
        libroGenero = new javax.swing.JPanel();
        cb_libroGenero = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        usuarioModificar = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        contraseñaModificar = new javax.swing.JTextField();
        fechaNacimientoModificar = new javax.swing.JTextField();
        numeroTelefonoModificar = new javax.swing.JTextField();
        correoModificar = new javax.swing.JTextField();
        bt_modificarUsuario = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        nombreCompletoModificar = new javax.swing.JTextField();
        generoFavoritoModificar = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        cb_amigosActuales = new javax.swing.JComboBox<>();
        bt_eliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        usuarioLabel = new javax.swing.JLabel();
        contraseñaLabel = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        CrearUsuario = new javax.swing.JLabel();
        entrar = new javax.swing.JButton();

        jLabel1.setText("Usuario: ");

        jLabel6.setText("Contraseña: ");

        jLabel3.setText("Fecha de nacimiento: ");

        jLabel4.setText("Número de Telefono: ");

        jLabel2.setText("Correo: ");

        jLabel5.setText("Género Favorito:");

        bt_crearUsuario.setText("Crear");
        bt_crearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearUsuarioMouseClicked(evt);
            }
        });

        jLabel26.setText("Nombre Completo:");

        generoFavorito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantansía", "Romance", "Acción", "Historia", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(usuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(47, 47, 47)
                        .addComponent(contraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(numeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(31, 31, 31)
                        .addComponent(nombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generoFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_crearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(usuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(contraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(numeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(nombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(generoFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(bt_crearUsuario)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFcrearUsuarioLayout = new javax.swing.GroupLayout(jFcrearUsuario.getContentPane());
        jFcrearUsuario.getContentPane().setLayout(jFcrearUsuarioLayout);
        jFcrearUsuarioLayout.setHorizontalGroup(
            jFcrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFcrearUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jFcrearUsuarioLayout.setVerticalGroup(
            jFcrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFcrearUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFadministrador.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Descripción:");
        AgregarLibro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel8.setText("Puntaje:");
        AgregarLibro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel9.setText("Copias Disponible:");
        AgregarLibro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel10.setText("Titulo:");
        AgregarLibro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel11.setText("Género: ");
        AgregarLibro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel12.setText("Edición:");
        AgregarLibro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel13.setText("Autor:");
        AgregarLibro.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel14.setText("Año Publicación:");
        AgregarLibro.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
        AgregarLibro.add(jt_añoPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 80, -1));
        AgregarLibro.add(jt_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, -1));
        AgregarLibro.add(jt_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));
        AgregarLibro.add(jt_copias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, -1));
        AgregarLibro.add(jt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        grupoPuntaje.add(rb_2);
        rb_2.setText("2");
        AgregarLibro.add(rb_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        grupoPuntaje.add(rb_3);
        rb_3.setText("3");
        AgregarLibro.add(rb_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        grupoPuntaje.add(rb_5);
        rb_5.setText("5");
        AgregarLibro.add(rb_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        grupoPuntaje.add(rb_1);
        rb_1.setSelected(true);
        rb_1.setText("1");
        AgregarLibro.add(rb_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        grupoPuntaje.add(rb_4);
        rb_4.setText("4");
        AgregarLibro.add(rb_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jTdescripcion.setColumns(20);
        jTdescripcion.setRows(5);
        jScrollPane1.setViewportView(jTdescripcion);

        AgregarLibro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Crear Libro");
        AgregarLibro.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 80, 20));

        jb_crearLibro.setText("Crear");
        jb_crearLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearLibroMouseClicked(evt);
            }
        });
        AgregarLibro.add(jb_crearLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 30));

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantansía", "Romance", "Acción", "Historia", " " }));
        AgregarLibro.add(cb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, -1));

        jLabel27.setText("Valor:");
        AgregarLibro.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));
        AgregarLibro.add(j_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 100, 30));

        jTabbedPane1.addTab("Agregar", AgregarLibro);

        Modificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Descripción:");
        Modificar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel17.setText("Puntaje:");
        Modificar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel18.setText("Copias Disponible:");
        Modificar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel19.setText("Titulo:");
        Modificar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel20.setText("Género: ");
        Modificar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel21.setText("Edición:");
        Modificar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel22.setText("Autor:");
        Modificar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel23.setText("Año Publicación:");
        Modificar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));
        Modificar.add(jt_añoPublicacionnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 80, -1));
        Modificar.add(jt_edicionNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 70, -1));
        Modificar.add(jt_autorNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));
        Modificar.add(jt_copiasNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, -1));
        Modificar.add(jt_tituloNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        grupoPuntaje.add(rb_2_);
        rb_2_.setText("2");
        Modificar.add(rb_2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        grupoPuntaje.add(rb_3_);
        rb_3_.setText("3");
        Modificar.add(rb_3_, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        grupoPuntaje.add(rb_5_);
        rb_5_.setText("5");
        Modificar.add(rb_5_, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        grupoPuntaje.add(rb_1_);
        rb_1_.setText("1");
        Modificar.add(rb_1_, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        grupoPuntaje.add(rb_4_);
        rb_4_.setText("4");
        Modificar.add(rb_4_, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jTdescripcionNuevo.setColumns(20);
        jTdescripcionNuevo.setRows(5);
        jScrollPane2.setViewportView(jTdescripcionNuevo);

        Modificar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 50));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Modificar Libro");
        Modificar.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, 20));

        jb_modificarLibro.setText("Modificar");
        jb_modificarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarLibroMouseClicked(evt);
            }
        });
        Modificar.add(jb_modificarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 80, 30));

        cb_libros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_librosItemStateChanged(evt);
            }
        });
        Modificar.add(cb_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, -1));

        EliminarLibro.setText("Eliminar");
        EliminarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarLibroMouseClicked(evt);
            }
        });
        Modificar.add(EliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, 30));

        nuevoGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantansía", "Romance", "Acción", "Historia", " " }));
        Modificar.add(nuevoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 100, -1));

        jLabel25.setText("Valor:");
        Modificar.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));
        Modificar.add(jt_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 90, 30));

        jTabbedPane1.addTab("Modificar", Modificar);

        jButton1.setText("Cerrar Sesión");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cerrar Sesión", jPanel4);

        jFadministrador.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 447, 352));

        jFUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(cb_librosAdquiridos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(cb_librosAdquiridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lista Libros", jPanel3);

        jLabel28.setText("Libros:");

        cb_libroadquiridos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_libroadquiridosItemStateChanged(evt);
            }
        });

        jLabel29.setText("Amigos:");

        cb_amigos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_amigosItemStateChanged(evt);
            }
        });

        PrestarLibro.setText("Prestar");
        PrestarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrestarLibroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_libroadquiridos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_amigos, 0, 104, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(PrestarLibro)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cb_libroadquiridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cb_amigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(PrestarLibro)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Prestamo Libros", jPanel5);

        panelSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSolicitudesMouseClicked(evt);
            }
        });

        AgregarAmigo.setText("Agregar");
        AgregarAmigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarAmigoMouseClicked(evt);
            }
        });

        cb_solicitudes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_solicitudesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelSolicitudesLayout = new javax.swing.GroupLayout(panelSolicitudes);
        panelSolicitudes.setLayout(panelSolicitudesLayout);
        panelSolicitudesLayout.setHorizontalGroup(
            panelSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSolicitudesLayout.createSequentialGroup()
                .addGroup(panelSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSolicitudesLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(AgregarAmigo))
                    .addGroup(panelSolicitudesLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(cb_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        panelSolicitudesLayout.setVerticalGroup(
            panelSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSolicitudesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cb_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(AgregarAmigo)
                .addGap(73, 73, 73))
        );

        jTabbedPane2.addTab("Solicitudes", panelSolicitudes);

        panelAgregarAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAgregarAmigosMouseClicked(evt);
            }
        });

        EnviarSolicitud.setText("Enviar Solicitud");
        EnviarSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnviarSolicitudMouseClicked(evt);
            }
        });

        cb_Usuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_UsuariosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarAmigosLayout = new javax.swing.GroupLayout(panelAgregarAmigos);
        panelAgregarAmigos.setLayout(panelAgregarAmigosLayout);
        panelAgregarAmigosLayout.setHorizontalGroup(
            panelAgregarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarAmigosLayout.createSequentialGroup()
                .addGroup(panelAgregarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarAmigosLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(EnviarSolicitud))
                    .addGroup(panelAgregarAmigosLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(cb_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        panelAgregarAmigosLayout.setVerticalGroup(
            panelAgregarAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarAmigosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(cb_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(EnviarSolicitud)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar Amigos", panelAgregarAmigos);

        libroGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libroGeneroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout libroGeneroLayout = new javax.swing.GroupLayout(libroGenero);
        libroGenero.setLayout(libroGeneroLayout);
        libroGeneroLayout.setHorizontalGroup(
            libroGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libroGeneroLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(cb_libroGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        libroGeneroLayout.setVerticalGroup(
            libroGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libroGeneroLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(cb_libroGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Libros según genero", libroGenero);

        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel30.setText("Usuario: ");

        jLabel31.setText("Contraseña: ");

        jLabel32.setText("Fecha de nacimiento: ");

        jLabel33.setText("Número de Telefono: ");

        jLabel34.setText("Correo: ");

        jLabel35.setText("Género Favorito:");

        bt_modificarUsuario.setText("Modificar");
        bt_modificarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarUsuarioMouseClicked(evt);
            }
        });

        jLabel36.setText("Nombre Completo:");

        generoFavoritoModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantansía", "Romance", "Acción", "Historia", " " }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(37, 37, 37)
                        .addComponent(usuarioModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(47, 47, 47)
                        .addComponent(contraseñaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(35, 35, 35)
                        .addComponent(fechaNacimientoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(26, 26, 26)
                        .addComponent(numeroTelefonoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(31, 31, 31)
                        .addComponent(nombreCompletoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(50, 50, 50)
                        .addComponent(correoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(28, 28, 28)
                        .addComponent(generoFavoritoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_modificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(usuarioModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(contraseñaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(fechaNacimientoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(numeroTelefonoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(nombreCompletoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(correoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(generoFavoritoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_modificarUsuario)
                .addGap(44, 44, 44))
        );

        jTabbedPane2.addTab("Modificar", jPanel7);

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        cb_amigosActuales.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_amigosActualesItemStateChanged(evt);
            }
        });
        cb_amigosActuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_amigosActualesActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(cb_amigosActuales, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_eliminar)
                .addGap(186, 186, 186))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(cb_amigosActuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(bt_eliminar)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar Amigos", jPanel6);

        jFUsuario.getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 455, 344));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioLabel.setText("Usuario: ");
        jPanel1.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        contraseñaLabel.setText("Contraseña: ");
        jPanel1.add(contraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, -1));
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, -1));

        CrearUsuario.setForeground(new java.awt.Color(0, 0, 255));
        CrearUsuario.setText("Crear Usuario");
        CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(CrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        entrar.setText("Entrar");
        entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarMouseClicked(evt);
            }
        });
        jPanel1.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseClicked
        // TODO add your handling code here:
        jFcrearUsuario.setVisible(true);
        jFcrearUsuario.setSize(433, 425);
    }//GEN-LAST:event_CrearUsuarioMouseClicked

    private void bt_crearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearUsuarioMouseClicked
        // TODO add your handling code here:
        String usuario;
        String contraseña;
        String fechanacimiento;
        String correo;
        String nombreCompleto;
        int numerotelefono;
        String generoLibros;
        try {
            usuario = usuarioNuevo.getText();
            contraseña = contraseñaNueva.getText();
            fechanacimiento = fechaNacimiento.getText();
            correo = this.correo.getText();
            numerotelefono = Integer.parseInt(numeroTelefono.getText());
            nombreCompleto = this.nombreCompleto.getText();
            generoLibros = generoFavorito.getSelectedItem().toString();
            listaUsuarios.add(new Persona(usuario, contraseña, fechanacimiento, correo, nombreCompleto, generoLibros));

            DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_Usuarios.getModel();
            modelo.addElement(new Persona(usuario, contraseña, fechanacimiento, correo, nombreCompleto, generoLibros));
            cb_Usuarios.setModel(modelo);
            
            JOptionPane.showMessageDialog(jFcrearUsuario, "Usuario almacenado exitosamente");

            usuarioNuevo.setText("");
            contraseñaNueva.setText("");
            fechaNacimiento.setText("");
            this.correo.setText("");
            numeroTelefono.setText("");
            this.nombreCompleto.setText("");
            generoFavorito.setSelectedIndex(0);
            jFcrearUsuario.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_bt_crearUsuarioMouseClicked

    private void jb_crearLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearLibroMouseClicked
        // TODO add your handling code here:
        String titulo;
        String descripcion;
        int puntaje = 0;
        int copias;
        String genero;
        double valor = 0;
        String autor;
        int año;
        int edicion;

        try {
            titulo = jt_titulo.getText();
            descripcion = jTdescripcion.getText();
            if (rb_1.isSelected()) {
                puntaje = 1;
            }
            if (rb_2.isSelected()) {
                puntaje = 2;
            }
            if (rb_3.isSelected()) {
                puntaje = 3;
            }
            if (rb_4.isSelected()) {
                puntaje = 4;
            }
            if (rb_5.isSelected()) {
                puntaje = 5;
            }
            copias = Integer.parseInt(jt_copias.getText());
            genero = cb_genero.getSelectedItem().toString();
            valor = Double.parseDouble(j_valor.getText());
            año = Integer.parseInt(jt_añoPublicacion.getText());
            edicion = Integer.parseInt(jt_edicion.getText());
            autor = jt_autor.getText();

            listaLibros.add(new Libro(titulo, descripcion, puntaje, copias, genero, valor, autor, año, edicion));

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros.getModel();
            modelo.addElement(new Libro(titulo, descripcion, puntaje, copias, genero, valor, autor, año, edicion));
            cb_libros.setModel(modelo);

            JOptionPane.showMessageDialog(jFadministrador, "Libro almacenado exitosamente");

            jt_titulo.setText("");
            jTdescripcion.setText("");
            rb_1.setSelected(true);
            rb_2.setSelected(false);
            rb_3.setSelected(false);
            rb_4.setSelected(false);
            rb_5.setSelected(false);
            jt_copias.setText("");
            cb_genero.setSelectedIndex(0);
            jt_autor.setText("");
            jt_edicion.setText("");
            j_valor.setText("");
            jt_añoPublicacion.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jFadministrador, "Ocurrió un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_jb_crearLibroMouseClicked

    private void entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseClicked
        // TODO add your handling code here:
        if ((usuario.getText().equals("admin")) && (contraseña.getText().equals("1111"))) {
            jFadministrador.setSize(460, 400);
            jFadministrador.setLocationRelativeTo(this);
            jFadministrador.setVisible(true);
            this.setVisible(false);
        } else {
            boolean usuarioPrueba = false;
            boolean contraseñaPrueba = false;
            for (int i = 0; i < listaUsuarios.size(); i++) {
                if (usuario.getText().equals(listaUsuarios.get(i).getUsuario())) {
                    usuarioPrueba = true;
                }
                if (contraseña.getText().equals(listaUsuarios.get(i).getContraseña())) {
                    contraseñaPrueba = true;
                }
                if (usuarioPrueba && contraseñaPrueba) {
                    usuarioActual = listaUsuarios.get(i);
                }
            }
            if (usuarioPrueba && contraseñaPrueba) {
                jFUsuario.setSize(455, 344);
                jFUsuario.setLocationRelativeTo(this);
                jFUsuario.setVisible(true);
                this.setVisible(false);

            }
        }
        usuario.setText("");
        contraseña.setText("");

    }//GEN-LAST:event_entrarMouseClicked

    private void jb_modificarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarLibroMouseClicked
        // TODO add your handling code here:
        String titulo;
        String descripcion;
        int copias;
        String genero;
        double valor = 0;
        String autor;
        int año;
        int edicion;

        try {
            if (!jt_tituloNuevo.getText().equals("")) {
                titulo = jt_tituloNuevo.getText();
                listaLibros.get(libroModificar).setTitulo(titulo);
            }
            if (!jTdescripcionNuevo.getText().equals("")) {
                descripcion = jTdescripcionNuevo.getText();
                listaLibros.get(libroModificar).setDescripcion(descripcion);
            }
            if (rb_1.isSelected()) {
                listaLibros.get(libroModificar).setPuntaje(1);
            }
            if (rb_2.isSelected()) {
                listaLibros.get(libroModificar).setPuntaje(2);
            }
            if (rb_3.isSelected()) {
                listaLibros.get(libroModificar).setPuntaje(3);
            }
            if (rb_4.isSelected()) {
                listaLibros.get(libroModificar).setPuntaje(4);
            }
            if (rb_5.isSelected()) {
                listaLibros.get(libroModificar).setPuntaje(5);
            }
            if (!jt_copiasNuevo.getText().equals("")) {
                copias = Integer.parseInt(jt_copiasNuevo.getText());
                listaLibros.get(libroModificar).setCopias(copias);
            }
            genero = nuevoGenero.getSelectedItem().toString();
            listaLibros.get(libroModificar).setGenero(genero);
            if (!jt_valor.getText().equals("")) {
                valor = Double.parseDouble(jt_valor.getText());
                listaLibros.get(libroModificar).setValor(valor);
            }

            año = Integer.parseInt(jt_añoPublicacionnuevo.getText());
            listaLibros.get(libroModificar).setAño(año);
            edicion = Integer.parseInt(jt_edicionNuevo.getText());
            listaLibros.get(libroModificar).setEdicion(edicion);
            autor = jt_autorNuevo.getText();
            listaLibros.get(libroModificar).setAutor(autor);

            jt_tituloNuevo.setText("");
            jTdescripcionNuevo.setText("");
            rb_1.setSelected(true);
            rb_2.setSelected(false);
            rb_3.setSelected(false);
            rb_4.setSelected(false);
            rb_5.setSelected(false);
            jt_copiasNuevo.setText("");
            nuevoGenero.setSelectedIndex(0);
            jt_añoPublicacionnuevo.setText("");
            jt_edicionNuevo.setText("");
            jt_autorNuevo.setText("");
            jt_valor.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_jb_modificarLibroMouseClicked

    private void cb_librosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_librosItemStateChanged
        libroModificar = cb_libros.getSelectedIndex();
        jt_tituloNuevo.setText(listaLibros.get(libroModificar).getTitulo());
        jTdescripcionNuevo.setText(listaLibros.get(libroModificar).getDescripcion());
        jt_copiasNuevo.setText(String.valueOf(listaLibros.get(libroModificar).getCopias()));
        nuevoGenero.setSelectedIndex(0);
        jt_valor.setText(String.valueOf(listaLibros.get(libroModificar).getValor()));
        jt_añoPublicacionnuevo.setText(String.valueOf(listaLibros.get(libroModificar).getAño()));
        jt_edicionNuevo.setText(String.valueOf(listaLibros.get(libroModificar).getEdicion()));
        jt_autorNuevo.setText(listaLibros.get(libroModificar).getAutor());

    }//GEN-LAST:event_cb_librosItemStateChanged

    private void EliminarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarLibroMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros.getModel();
        modelo.removeElement(cb_libros.getSelectedIndex());
        cb_libros.setModel(modelo);
        listaLibros.remove(cb_libros.getSelectedIndex());
    }//GEN-LAST:event_EliminarLibroMouseClicked

    private void bt_modificarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_modificarUsuarioMouseClicked

    private void cb_libroadquiridosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_libroadquiridosItemStateChanged
        // TODO add your handling code here:
        libroPrestar = (Libro) cb_libroadquiridos.getSelectedItem();
    }//GEN-LAST:event_cb_libroadquiridosItemStateChanged

    private void cb_amigosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_amigosItemStateChanged
        amigoPrestar = (Persona) cb_amigos.getSelectedItem();
    }//GEN-LAST:event_cb_amigosItemStateChanged

    private void PrestarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrestarLibroMouseClicked
        // TODO add your handling code here:
        amigoPrestar.getListaLibros().add(libroPrestar);
        usuarioActual.getListaLibros().remove(libroPrestar);
        JOptionPane.showMessageDialog(jFUsuario, "Ha prestado un libro exitosamente");
    }//GEN-LAST:event_PrestarLibroMouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void EnviarSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarSolicitudMouseClicked
        // TODO add your handling code here:
        amigoEnviar.getAmigosEspera().add(usuarioActual);
        JOptionPane.showMessageDialog(jFUsuario, "Ha enviado una solicitud de amistad exitosamente");
    }//GEN-LAST:event_EnviarSolicitudMouseClicked

    private void cb_UsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_UsuariosItemStateChanged
        // TODO add your handling code here:
        amigoEnviar = (Persona) cb_Usuarios.getSelectedItem();
    }//GEN-LAST:event_cb_UsuariosItemStateChanged

    private void panelAgregarAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAgregarAmigosMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Usuarios.getModel();
        for (Persona temp : listaUsuarios) {
            if (!(temp.getUsuario().equals(usuarioActual.getUsuario()))) {
                modelo.addElement(temp);
            }
        }
        cb_Usuarios.setModel(modelo);
        

    }//GEN-LAST:event_panelAgregarAmigosMouseClicked

    private void panelSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSolicitudesMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_solicitudes.getModel();
        for (Persona temp : usuarioActual.getAmigosEspera()) {
            modelo.addElement(temp);
        }
    }//GEN-LAST:event_panelSolicitudesMouseClicked

    private void AgregarAmigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarAmigoMouseClicked
        // TODO add your handling code here:
        usuarioActual.getListaAmigos().add(amigoAceptar);
        usuarioActual.getAmigosEspera().remove(amigoAceptar);
    }//GEN-LAST:event_AgregarAmigoMouseClicked

    private void libroGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libroGeneroMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_libroGenero.getModel();
        for (int i = 0; i < listaLibros.size(); i++) {
            if (usuarioActual.getGeneroLibros().equals(listaLibros.get(i).getGenero())){
                modelo.addElement(listaLibros.get(i));
            }
        }
        cb_libroGenero.setModel(modelo);
    }//GEN-LAST:event_libroGeneroMouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void cb_solicitudesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_solicitudesItemStateChanged
        // TODO add your handling code here:
        amigoAceptar = (Persona)cb_solicitudes.getSelectedItem(); 
    }//GEN-LAST:event_cb_solicitudesItemStateChanged

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_librosAdquiridos.getModel();
        for (Libro temp : usuarioActual.getListaLibros()) {
            modelo.addElement(temp);
        }
        cb_librosAdquiridos.setModel(modelo);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void cb_amigosActualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_amigosActualesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_amigosActualesActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)cb_amigosActuales.getModel();
        for (Persona temp : usuarioActual.getListaAmigos()) {
            modelo.addElement(temp);
        }
        cb_amigosActuales.setModel(modelo);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
        // TODO add your handling code here:
        usuarioActual.getListaAmigos().remove(amigoEliminar);
    }//GEN-LAST:event_bt_eliminarMouseClicked

    private void cb_amigosActualesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_amigosActualesItemStateChanged
        // TODO add your handling code here:
        amigoEliminar = (Persona)cb_amigosActuales.getSelectedItem();
    }//GEN-LAST:event_cb_amigosActualesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    ArrayList<Libro> listaLibros = new ArrayList();
    ArrayList<Persona> listaUsuarios = new ArrayList();
    int libroModificar;
    Persona usuarioActual;
    Libro libroPrestar;
    Persona amigoPrestar;
    Persona amigoEnviar;
    Persona amigoAceptar;
    Persona amigoEliminar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAmigo;
    private javax.swing.JPanel AgregarLibro;
    private javax.swing.JLabel CrearUsuario;
    private javax.swing.JButton EliminarLibro;
    private javax.swing.JButton EnviarSolicitud;
    private javax.swing.JPanel Modificar;
    private javax.swing.JButton PrestarLibro;
    private javax.swing.JButton bt_crearUsuario;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificarUsuario;
    private javax.swing.JComboBox<String> cb_Usuarios;
    private javax.swing.JComboBox<String> cb_amigos;
    private javax.swing.JComboBox<String> cb_amigosActuales;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_libroGenero;
    private javax.swing.JComboBox<String> cb_libroadquiridos;
    private javax.swing.JComboBox<String> cb_libros;
    private javax.swing.JComboBox<String> cb_librosAdquiridos;
    private javax.swing.JComboBox<String> cb_solicitudes;
    private javax.swing.JTextField contraseña;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JTextField contraseñaModificar;
    private javax.swing.JTextField contraseñaNueva;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField correoModificar;
    private javax.swing.JButton entrar;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JTextField fechaNacimientoModificar;
    private javax.swing.JComboBox<String> generoFavorito;
    private javax.swing.JComboBox<String> generoFavoritoModificar;
    private javax.swing.ButtonGroup grupoPuntaje;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFUsuario;
    private javax.swing.JFrame jFadministrador;
    private javax.swing.JFrame jFcrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTdescripcion;
    private javax.swing.JTextArea jTdescripcionNuevo;
    private javax.swing.JTextField j_valor;
    private javax.swing.JButton jb_crearLibro;
    private javax.swing.JButton jb_modificarLibro;
    private javax.swing.JTextField jt_autor;
    private javax.swing.JTextField jt_autorNuevo;
    private javax.swing.JTextField jt_añoPublicacion;
    private javax.swing.JTextField jt_añoPublicacionnuevo;
    private javax.swing.JTextField jt_copias;
    private javax.swing.JTextField jt_copiasNuevo;
    private javax.swing.JTextField jt_edicion;
    private javax.swing.JTextField jt_edicionNuevo;
    private javax.swing.JTextField jt_titulo;
    private javax.swing.JTextField jt_tituloNuevo;
    private javax.swing.JTextField jt_valor;
    private javax.swing.JPanel libroGenero;
    private javax.swing.JTextField nombreCompleto;
    private javax.swing.JTextField nombreCompletoModificar;
    private javax.swing.JComboBox<String> nuevoGenero;
    private javax.swing.JTextField numeroTelefono;
    private javax.swing.JTextField numeroTelefonoModificar;
    private javax.swing.JPanel panelAgregarAmigos;
    private javax.swing.JPanel panelSolicitudes;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_1_;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JRadioButton rb_2_;
    private javax.swing.JRadioButton rb_3;
    private javax.swing.JRadioButton rb_3_;
    private javax.swing.JRadioButton rb_4;
    private javax.swing.JRadioButton rb_4_;
    private javax.swing.JRadioButton rb_5;
    private javax.swing.JRadioButton rb_5_;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioModificar;
    private javax.swing.JTextField usuarioNuevo;
    // End of variables declaration//GEN-END:variables
}
