/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg1_carlosnuila;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Nuila
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFcrearUsuario = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuarioNuevo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contraseñaNueva = new javax.swing.JTextField();
        fechaNacimiento = new javax.swing.JTextField();
        numeroTelefono = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        generoFavorito = new javax.swing.JTextField();
        bt_crearUsuario = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        nombreCompleto = new javax.swing.JTextField();
        jFadministrador = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AgregarLibro = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jt_añoPublicacion = new javax.swing.JTextField();
        jt_edicion = new javax.swing.JTextField();
        jt_autor = new javax.swing.JTextField();
        jt_copias = new javax.swing.JTextField();
        jt_titulo = new javax.swing.JTextField();
        rb_2 = new javax.swing.JRadioButton();
        rb_3 = new javax.swing.JRadioButton();
        rb_5 = new javax.swing.JRadioButton();
        rb_1 = new javax.swing.JRadioButton();
        rb_4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTdescripcion = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jb_crearLibro = new javax.swing.JButton();
        genero = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        Modificar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jt_añoPublicacionnuevo = new javax.swing.JTextField();
        jt_edicionNuevo = new javax.swing.JTextField();
        jt_autorNuevo = new javax.swing.JTextField();
        jt_copiasNuevo = new javax.swing.JTextField();
        jt_tituloNuevo = new javax.swing.JTextField();
        rb_2_ = new javax.swing.JRadioButton();
        rb_3_ = new javax.swing.JRadioButton();
        rb_5_ = new javax.swing.JRadioButton();
        rb_1_ = new javax.swing.JRadioButton();
        rb_4_ = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTdescripcionNuevo = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jb_modificarLibro = new javax.swing.JButton();
        cb_libros = new javax.swing.JComboBox<>();
        EliminarLibro = new javax.swing.JButton();
        nuevoGenero = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jt_valor = new javax.swing.JTextField();
        grupoPuntaje = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        usuarioLabel = new javax.swing.JLabel();
        contraseñaLabel = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        CrearUsuario = new javax.swing.JLabel();
        entrar = new javax.swing.JButton();

        jLabel1.setText("Usuario: ");

        jLabel6.setText("Contraseña: ");

        jLabel3.setText("Fecha de nacimiento: ");

        jLabel4.setText("Número de Telefono: ");

        jLabel2.setText("Correo: ");

        jLabel5.setText("Género Favorito:");

        bt_crearUsuario.setText("Crear");
        bt_crearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearUsuarioMouseClicked(evt);
            }
        });

        jLabel26.setText("Nombre Completo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(usuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6)
                        .addGap(47, 47, 47)
                        .addComponent(contraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(numeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel26)
                        .addGap(31, 31, 31)
                        .addComponent(nombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(generoFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(bt_crearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(usuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(contraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(numeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(nombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(generoFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bt_crearUsuario)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFcrearUsuarioLayout = new javax.swing.GroupLayout(jFcrearUsuario.getContentPane());
        jFcrearUsuario.getContentPane().setLayout(jFcrearUsuarioLayout);
        jFcrearUsuarioLayout.setHorizontalGroup(
            jFcrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFcrearUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jFcrearUsuarioLayout.setVerticalGroup(
            jFcrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFcrearUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFadministrador.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Descripción:");
        AgregarLibro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel8.setText("Puntaje:");
        AgregarLibro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel9.setText("Copias Disponible:");
        AgregarLibro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel10.setText("Titulo:");
        AgregarLibro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel11.setText("Género: ");
        AgregarLibro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel12.setText("Edición:");
        AgregarLibro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel13.setText("Autor:");
        AgregarLibro.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel14.setText("Año Publicación:");
        AgregarLibro.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
        AgregarLibro.add(jt_añoPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 80, -1));
        AgregarLibro.add(jt_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, -1));
        AgregarLibro.add(jt_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));
        AgregarLibro.add(jt_copias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, -1));

        jt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_tituloActionPerformed(evt);
            }
        });
        AgregarLibro.add(jt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        grupoPuntaje.add(rb_2);
        rb_2.setText("2");
        AgregarLibro.add(rb_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        grupoPuntaje.add(rb_3);
        rb_3.setText("3");
        AgregarLibro.add(rb_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        grupoPuntaje.add(rb_5);
        rb_5.setText("5");
        AgregarLibro.add(rb_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        grupoPuntaje.add(rb_1);
        rb_1.setSelected(true);
        rb_1.setText("1");
        AgregarLibro.add(rb_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        grupoPuntaje.add(rb_4);
        rb_4.setText("4");
        AgregarLibro.add(rb_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jTdescripcion.setColumns(20);
        jTdescripcion.setRows(5);
        jScrollPane1.setViewportView(jTdescripcion);

        AgregarLibro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Crear Libro");
        AgregarLibro.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 80, 20));

        jb_crearLibro.setText("Crear");
        jb_crearLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearLibroMouseClicked(evt);
            }
        });
        AgregarLibro.add(jb_crearLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 30));

        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantansía", "Romance", "Acción", "Historia", " " }));
        AgregarLibro.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, -1));

        jLabel27.setText("Valor:");
        AgregarLibro.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));
        AgregarLibro.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 100, 20));

        jTabbedPane1.addTab("Agregar", AgregarLibro);

        Modificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Descripción:");
        Modificar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel17.setText("Puntaje:");
        Modificar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel18.setText("Copias Disponible:");
        Modificar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel19.setText("Titulo:");
        Modificar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel20.setText("Género: ");
        Modificar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel21.setText("Edición:");
        Modificar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel22.setText("Autor:");
        Modificar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel23.setText("Año Publicación:");
        Modificar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));
        Modificar.add(jt_añoPublicacionnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 80, -1));
        Modificar.add(jt_edicionNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 70, -1));
        Modificar.add(jt_autorNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));
        Modificar.add(jt_copiasNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, -1));

        jt_tituloNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_tituloNuevoActionPerformed(evt);
            }
        });
        Modificar.add(jt_tituloNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        grupoPuntaje.add(rb_2_);
        rb_2_.setText("2");
        Modificar.add(rb_2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        grupoPuntaje.add(rb_3_);
        rb_3_.setText("3");
        Modificar.add(rb_3_, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        grupoPuntaje.add(rb_5_);
        rb_5_.setText("5");
        Modificar.add(rb_5_, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        grupoPuntaje.add(rb_1_);
        rb_1_.setText("1");
        Modificar.add(rb_1_, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        grupoPuntaje.add(rb_4_);
        rb_4_.setText("4");
        Modificar.add(rb_4_, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jTdescripcionNuevo.setColumns(20);
        jTdescripcionNuevo.setRows(5);
        jScrollPane2.setViewportView(jTdescripcionNuevo);

        Modificar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 50));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Modificar Libro");
        Modificar.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, 20));

        jb_modificarLibro.setText("Modificar");
        Modificar.add(jb_modificarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 80, 30));

        Modificar.add(cb_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, -1));

        EliminarLibro.setText("Eliminar");
        Modificar.add(EliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, 30));

        nuevoGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantansía", "Romance", "Acción", "Historia", " " }));
        Modificar.add(nuevoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 100, -1));

        jLabel25.setText("Valor:");
        Modificar.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));
        Modificar.add(jt_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 90, 20));

        jTabbedPane1.addTab("Modificar", Modificar);

        jFadministrador.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 447, 352));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioLabel.setText("Usuario: ");
        jPanel1.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        contraseñaLabel.setText("Contraseña: ");
        jPanel1.add(contraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, -1));
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, -1));

        CrearUsuario.setForeground(new java.awt.Color(0, 0, 255));
        CrearUsuario.setText("Crear Usuario");
        CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(CrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        entrar.setText("Entrar");
        entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarMouseClicked(evt);
            }
        });
        jPanel1.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseClicked
        // TODO add your handling code here:
        jFcrearUsuario.setVisible(true);
        jFcrearUsuario.setSize(433, 425);
    }//GEN-LAST:event_CrearUsuarioMouseClicked

    private void jt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_tituloActionPerformed

    private void jt_tituloNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_tituloNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_tituloNuevoActionPerformed

    private void bt_crearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearUsuarioMouseClicked
        // TODO add your handling code here:
        String usuario;
        String contraseña;
        String fechanacimiento;
        String correo;
        String nombreCompleto;
        int numerotelefono;
        String generoLibros;
        try {
            usuario = usuarioNuevo.getText();
            contraseña = contraseñaNueva.getText();
            fechanacimiento = fechaNacimiento.getText();
            correo = this.correo.getText();
            numerotelefono = Integer.parseInt(numeroTelefono.getText());
            nombreCompleto = this.nombreCompleto.getText();
            generoLibros = generoFavorito.getText();
            listaUsuarios.add(new Persona(usuario, contraseña, fechanacimiento, correo, nombreCompleto, generoLibros));

            JOptionPane.showMessageDialog(this, "Usuario almacenado exitosamente");
            
            usuarioNuevo.setText("");
            contraseñaNueva.setText("");
            fechaNacimiento.setText("");
            this.correo.setText("");
            numeroTelefono.setText("");
            this.nombreCompleto.setText("");
            generoFavorito.setText("");
            jFcrearUsuario.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_bt_crearUsuarioMouseClicked

    private void jb_crearLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearLibroMouseClicked
        // TODO add your handling code here:
        String titulo;
        String descripcion;
        int puntaje = 0;
        int copias;
        String genero;
        double valor = 0;
        String autor = "";
        try {
            titulo = jt_titulo.getText();
            descripcion = jTdescripcion.getText();
            if (rb_1.isSelected()) {
                puntaje = 1;
            }
            if (rb_2.isSelected()) {
                puntaje = 2;
            }
            if (rb_3.isSelected()) {
                puntaje = 3;
            }
            if (rb_4.isSelected()) {
                puntaje = 4;
            }
            if (rb_5.isSelected()) {
                puntaje = 5;
            }
            copias = Integer.parseInt(jt_copias.getText());
            genero = this.genero.getSelectedItem().toString();
            valor = Double.parseDouble(this.valor.getText());

            listaLibros.add(new Libro(titulo, descripcion, puntaje, copias, genero, valor, autor));

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros.getModel();
            modelo.addElement(new Libro(titulo, descripcion, puntaje, copias, genero, valor, autor));
            cb_libros.setModel(modelo);

            JOptionPane.showMessageDialog(this, "Libro almacenado exitosamente");
            
            jt_titulo.setText("");
            jTdescripcion.setText("");
            rb_1.setSelected(true);
            rb_2.setSelected(false);
            rb_3.setSelected(false);
            rb_4.setSelected(false);
            rb_5.setSelected(false);
            jt_copias.setText("");
            this.genero.setSelectedIndex(0);
            this.valor.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_jb_crearLibroMouseClicked

    private void entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseClicked
        // TODO add your handling code here:
        if ((usuario.getText().equals("admin")) && (contraseña.getText().equals("1111"))) {
            jFadministrador.setSize(460, 400);
            jFadministrador.setLocationRelativeTo(this);
            jFadministrador.setVisible(true);
        }

    }//GEN-LAST:event_entrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    ArrayList<Libro> listaLibros = new ArrayList();
    ArrayList<Persona> listaUsuarios = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarLibro;
    private javax.swing.JLabel CrearUsuario;
    private javax.swing.JButton EliminarLibro;
    private javax.swing.JPanel Modificar;
    private javax.swing.JButton bt_crearUsuario;
    private javax.swing.JComboBox<String> cb_libros;
    private javax.swing.JTextField contraseña;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JTextField contraseñaNueva;
    private javax.swing.JTextField correo;
    private javax.swing.JButton entrar;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JTextField generoFavorito;
    private javax.swing.ButtonGroup grupoPuntaje;
    private javax.swing.JFrame jFadministrador;
    private javax.swing.JFrame jFcrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTdescripcion;
    private javax.swing.JTextArea jTdescripcionNuevo;
    private javax.swing.JButton jb_crearLibro;
    private javax.swing.JButton jb_modificarLibro;
    private javax.swing.JTextField jt_autor;
    private javax.swing.JTextField jt_autorNuevo;
    private javax.swing.JTextField jt_añoPublicacion;
    private javax.swing.JTextField jt_añoPublicacionnuevo;
    private javax.swing.JTextField jt_copias;
    private javax.swing.JTextField jt_copiasNuevo;
    private javax.swing.JTextField jt_edicion;
    private javax.swing.JTextField jt_edicionNuevo;
    private javax.swing.JTextField jt_titulo;
    private javax.swing.JTextField jt_tituloNuevo;
    private javax.swing.JTextField jt_valor;
    private javax.swing.JTextField nombreCompleto;
    private javax.swing.JComboBox<String> nuevoGenero;
    private javax.swing.JTextField numeroTelefono;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_1_;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JRadioButton rb_2_;
    private javax.swing.JRadioButton rb_3;
    private javax.swing.JRadioButton rb_3_;
    private javax.swing.JRadioButton rb_4;
    private javax.swing.JRadioButton rb_4_;
    private javax.swing.JRadioButton rb_5;
    private javax.swing.JRadioButton rb_5_;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioNuevo;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
