/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg1_carlosnuila;

/**
 *
 * @author Carlos Nuila
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFcrearUsuario = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuarioNuevo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contraseñaNueva = new javax.swing.JTextField();
        fechaNacimiento = new javax.swing.JTextField();
        numeroTelefono = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        generoFavorito = new javax.swing.JTextField();
        bt_crearUsuario = new javax.swing.JButton();
        jFadministrador = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AgregarLibro = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jt_añoPublicacion = new javax.swing.JTextField();
        jt_edicion = new javax.swing.JTextField();
        jt_autor = new javax.swing.JTextField();
        jt_copias = new javax.swing.JTextField();
        jt_titulo = new javax.swing.JTextField();
        historia = new javax.swing.JCheckBox();
        fantasia = new javax.swing.JCheckBox();
        romance = new javax.swing.JCheckBox();
        accion = new javax.swing.JCheckBox();
        rb_2 = new javax.swing.JRadioButton();
        rb_3 = new javax.swing.JRadioButton();
        rb_5 = new javax.swing.JRadioButton();
        rb_1 = new javax.swing.JRadioButton();
        rb_4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTdescripcion = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jb_crearLibro = new javax.swing.JButton();
        Modificar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jt_añoPublicacionnuevo = new javax.swing.JTextField();
        jt_edicionNuevo = new javax.swing.JTextField();
        jt_autorNuevo = new javax.swing.JTextField();
        jt_copiasNuevo = new javax.swing.JTextField();
        jt_tituloNuevo = new javax.swing.JTextField();
        historia1 = new javax.swing.JCheckBox();
        fantasia1 = new javax.swing.JCheckBox();
        romance1 = new javax.swing.JCheckBox();
        accion1 = new javax.swing.JCheckBox();
        rb_2_ = new javax.swing.JRadioButton();
        rb_3_ = new javax.swing.JRadioButton();
        rb_5_ = new javax.swing.JRadioButton();
        rb_1_ = new javax.swing.JRadioButton();
        rb_4_ = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTdescripcionNuevo = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jb_modificarLibro = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        EliminarLibro = new javax.swing.JButton();
        grupoPuntaje = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        usuarioLabel = new javax.swing.JLabel();
        contraseñaLabel = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contraseña2 = new javax.swing.JTextField();
        CrearUsuario = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel6.setText("Contraseña: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel3.setText("Fecha de nacimiento: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel4.setText("Número de Telefono: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        jPanel2.add(usuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 110, -1));

        jLabel2.setText("Correo: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel5.setText("Género Favorito:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        jPanel2.add(contraseñaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, -1));
        jPanel2.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, -1));
        jPanel2.add(numeroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 130, -1));
        jPanel2.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 150, -1));
        jPanel2.add(generoFavorito, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, -1));

        bt_crearUsuario.setText("Crear");
        jPanel2.add(bt_crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 110, -1));

        javax.swing.GroupLayout jFcrearUsuarioLayout = new javax.swing.GroupLayout(jFcrearUsuario.getContentPane());
        jFcrearUsuario.getContentPane().setLayout(jFcrearUsuarioLayout);
        jFcrearUsuarioLayout.setHorizontalGroup(
            jFcrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        jFcrearUsuarioLayout.setVerticalGroup(
            jFcrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFcrearUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFadministrador.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Descripción:");
        AgregarLibro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel8.setText("Puntaje:");
        AgregarLibro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel9.setText("Copias Disponible:");
        AgregarLibro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel10.setText("Titulo:");
        AgregarLibro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel11.setText("Género: ");
        AgregarLibro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel12.setText("Edición:");
        AgregarLibro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel13.setText("Autor:");
        AgregarLibro.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel14.setText("Año Publicación:");
        AgregarLibro.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));
        AgregarLibro.add(jt_añoPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 80, -1));
        AgregarLibro.add(jt_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, -1));
        AgregarLibro.add(jt_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));
        AgregarLibro.add(jt_copias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, -1));

        jt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_tituloActionPerformed(evt);
            }
        });
        AgregarLibro.add(jt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        historia.setText("Historia");
        AgregarLibro.add(historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        fantasia.setText("Fantasía");
        AgregarLibro.add(fantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        romance.setText("Romance");
        AgregarLibro.add(romance, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        accion.setText("Acción");
        AgregarLibro.add(accion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        grupoPuntaje.add(rb_2);
        rb_2.setText("2");
        AgregarLibro.add(rb_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        grupoPuntaje.add(rb_3);
        rb_3.setText("3");
        AgregarLibro.add(rb_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        grupoPuntaje.add(rb_5);
        rb_5.setText("5");
        AgregarLibro.add(rb_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        grupoPuntaje.add(rb_1);
        rb_1.setText("1");
        AgregarLibro.add(rb_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        grupoPuntaje.add(rb_4);
        rb_4.setText("4");
        AgregarLibro.add(rb_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jTdescripcion.setColumns(20);
        jTdescripcion.setRows(5);
        jScrollPane1.setViewportView(jTdescripcion);

        AgregarLibro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Crear Libro");
        AgregarLibro.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 80, 20));

        jb_crearLibro.setText("Crear");
        AgregarLibro.add(jb_crearLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 100, 30));

        jTabbedPane1.addTab("Agregar", AgregarLibro);

        Modificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Descripción:");
        Modificar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel17.setText("Puntaje:");
        Modificar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel18.setText("Copias Disponible:");
        Modificar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel19.setText("Titulo:");
        Modificar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel20.setText("Género: ");
        Modificar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel21.setText("Edición:");
        Modificar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel22.setText("Autor:");
        Modificar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel23.setText("Año Publicación:");
        Modificar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));
        Modificar.add(jt_añoPublicacionnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 80, -1));
        Modificar.add(jt_edicionNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, -1));
        Modificar.add(jt_autorNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));
        Modificar.add(jt_copiasNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, -1));

        jt_tituloNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_tituloNuevoActionPerformed(evt);
            }
        });
        Modificar.add(jt_tituloNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        historia1.setText("Historia");
        Modificar.add(historia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        fantasia1.setText("Fantasía");
        Modificar.add(fantasia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        romance1.setText("Romance");
        Modificar.add(romance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        accion1.setText("Acción");
        Modificar.add(accion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        grupoPuntaje.add(rb_2_);
        rb_2_.setText("2");
        Modificar.add(rb_2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        grupoPuntaje.add(rb_3_);
        rb_3_.setText("3");
        Modificar.add(rb_3_, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        grupoPuntaje.add(rb_5_);
        rb_5_.setText("5");
        Modificar.add(rb_5_, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        grupoPuntaje.add(rb_1_);
        rb_1_.setSelected(true);
        rb_1_.setText("1");
        Modificar.add(rb_1_, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        grupoPuntaje.add(rb_4_);
        rb_4_.setText("4");
        Modificar.add(rb_4_, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jTdescripcionNuevo.setColumns(20);
        jTdescripcionNuevo.setRows(5);
        jScrollPane2.setViewportView(jTdescripcionNuevo);

        Modificar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 50));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Modificar Libro");
        Modificar.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, 20));

        jb_modificarLibro.setText("Modificar");
        Modificar.add(jb_modificarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 80, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Modificar.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        EliminarLibro.setText("Eliminar");
        Modificar.add(EliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, 30));

        jTabbedPane1.addTab("Modificar", Modificar);

        jFadministrador.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 447, 352));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioLabel.setText("Usuario: ");
        jPanel1.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        contraseñaLabel.setText("Contraseña: ");
        jPanel1.add(contraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, -1));
        jPanel1.add(contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, -1));

        CrearUsuario.setForeground(new java.awt.Color(0, 0, 255));
        CrearUsuario.setText("Crear Usuario");
        CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(CrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseClicked
        // TODO add your handling code here:
        jFcrearUsuario.setVisible(true);
        
    }//GEN-LAST:event_CrearUsuarioMouseClicked

    private void jt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_tituloActionPerformed

    private void jt_tituloNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_tituloNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_tituloNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarLibro;
    private javax.swing.JLabel CrearUsuario;
    private javax.swing.JButton EliminarLibro;
    private javax.swing.JPanel Modificar;
    private javax.swing.JCheckBox accion;
    private javax.swing.JCheckBox accion1;
    private javax.swing.JButton bt_crearUsuario;
    private javax.swing.JTextField contraseña2;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JTextField contraseñaNueva;
    private javax.swing.JTextField correo;
    private javax.swing.JCheckBox fantasia;
    private javax.swing.JCheckBox fantasia1;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JTextField generoFavorito;
    private javax.swing.ButtonGroup grupoPuntaje;
    private javax.swing.JCheckBox historia;
    private javax.swing.JCheckBox historia1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFadministrador;
    private javax.swing.JFrame jFcrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTdescripcion;
    private javax.swing.JTextArea jTdescripcionNuevo;
    private javax.swing.JButton jb_crearLibro;
    private javax.swing.JButton jb_modificarLibro;
    private javax.swing.JTextField jt_autor;
    private javax.swing.JTextField jt_autorNuevo;
    private javax.swing.JTextField jt_añoPublicacion;
    private javax.swing.JTextField jt_añoPublicacionnuevo;
    private javax.swing.JTextField jt_copias;
    private javax.swing.JTextField jt_copiasNuevo;
    private javax.swing.JTextField jt_edicion;
    private javax.swing.JTextField jt_edicionNuevo;
    private javax.swing.JTextField jt_titulo;
    private javax.swing.JTextField jt_tituloNuevo;
    private javax.swing.JTextField numeroTelefono;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_1_;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JRadioButton rb_2_;
    private javax.swing.JRadioButton rb_3;
    private javax.swing.JRadioButton rb_3_;
    private javax.swing.JRadioButton rb_4;
    private javax.swing.JRadioButton rb_4_;
    private javax.swing.JRadioButton rb_5;
    private javax.swing.JRadioButton rb_5_;
    private javax.swing.JCheckBox romance;
    private javax.swing.JCheckBox romance1;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioNuevo;
    // End of variables declaration//GEN-END:variables
}
